name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: rendau
      IMAGE: limelog_fe
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set-up node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13'

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build

      - name: Docker login
        run: |
          echo ${{ secrets.CR_PAT }} | docker login -u $OWNER --password-stdin ghcr.io

      - name: Docker build
        run: |
          docker build -t ghcr.io/$OWNER/$IMAGE:latest .

      - name: Docker push
        run: |
          docker push ghcr.io/$OWNER/$IMAGE:latest
