name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      IMAGE: limelog_fe
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set-up node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13'

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t cr.yandex/${{  secrets.CR_YANDEX_ID }}/$IMAGE:latest .

      - name: Docker login
        run: docker login -u=json_key -p='${{  secrets.CR_YANDEX_PASSWORD }}' cr.yandex

      - name: Docker push
        run: docker push cr.yandex/${{  secrets.CR_YANDEX_ID }}/$IMAGE:latest
